name: Trigger auto deployment for redditcollector

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/redditcollector-AutoDeployTrigger-e04914f0-7dbd-4b1b-8b62-454c296b958f.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.REDDITCOLLECTOR_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.REDDITCOLLECTOR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REDDITCOLLECTOR_REGISTRY_PASSWORD }}
          containerAppName: redditcollector
          resourceGroup: brandy.io_dev
          imageToBuild: soumitsr/redditcollector:${{ github.sha }}
          
            

     

